In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC #suport vector machine
from sklearn.ensemble import RandomForestClassifier #co su dung dung thuat toan random forest
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits() #danh gia datasets digit su dung sklearn

from sklearn.model_selection import train_test_split #chia data train - test
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [3]:
#hoi quy logistic regression
lo = LogisticRegression()
lo.fit(x_train, y_train)
print(lo.score(x_test, y_test))

0.9555555555555556


C:\Users\ainzo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
#hoi quy SVM
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9851851851851852

In [5]:
#model random forest
rf= RandomForestClassifier( n_estimators = 40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9611111111111111

In [6]:
#use KFold de danh gia cac mo hinh
from sklearn.model_selection import KFold
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
a1 = [1,2,3,4,5,6,7,8,9] #array test de chia train/test
for train, test in kf.split(a1):
    print(train, test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, x_train, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold #stratifiedkfold giong kfold nhung tot hon
folds = StratifiedKFold(n_splits = 3)

In [10]:
score_1 = []
score_svm = []
score_rf = []
for train, test in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train], digits.data[test], digits.target[train], digits.target[test]
    score_1.append(get_score(LogisticRegression(), x_train, y_train, y_test)) #so sanh cung luc 3 model
    score_svm.append(get_score(SVC(), x_train, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators = 40), x_train, y_train, y_test))

C:\Users\ainzo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ainzo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [11]:
print(score_1, '\n', score_svm, '\n', score_rf)

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468] 
 [0.9666110183639399, 0.9816360601001669, 0.9549248747913188] 
 [0.9332220367278798, 0.9449081803005008, 0.9265442404006677]


In [12]:
#cross_val_score
#code o dong [54] co the thay the bang cross_validation sklearn
from sklearn.model_selection import cross_val_score
print(cross_val_score(LogisticRegression(), digits.data, digits.target))#logisticregression
print(cross_val_score(SVC(), digits.data, digits.target))
print(cross_val_score(RandomForestClassifier(), digits.data, digits.target))

C:\Users\ainzo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ainzo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.93055556 0.91388889 0.95543175 0.96657382 0.92479109]
